# Generated by Django 3.2.10 on 2022-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
