# Generated by Django 3.2.10 on 2022-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='image',
            field=models.ImageField(null=True, upload_to='fish'),
        ),
    ]
