# Generated by Django 3.2.10 on 2022-02-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_fish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='added_date',
        ),
        migrations.AlterField(
            model_name='fish',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
