# Generated by Django 3.2.10 on 2022-02-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_auto_20220216_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='image',
            new_name='photo',
        ),
    ]
