# Generated by Django 3.2.10 on 2022-02-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_rename_image_fish_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='photo',
            new_name='image',
        ),
    ]
